### ISSUE TITLE
Integrate current auction - view only

### ISSUE THREAD

**Issue by dblodorn** [public-assembly/public-assembly-home-page#16]
- [x] create hook with data endpoint / provider pattern
- [ ] write rendering components

Can build this internally to start although should be easy to port over to a package

<img width="767" alt="Screen Shot 2022-12-01 at 9 44 57 AM" src="https://user-images.githubusercontent.com/7268786/205082280-b454dafa-f3dd-4a27-adb1-052b80356974.png">

**Comment by 0xTranqui** [comment]
<img width="632" alt="Screen Shot 2022-12-01 at 5 04 49 PM" src="https://user-images.githubusercontent.com/93691906/205168828-0eea803b-0074-4db2-a11c-4afbd0dfdfd0.png">

the design for this view will look much more like this ^ than what is shown in the screenshot above. here is the [figma](https://www.figma.com/file/WuYez6CDjrNEAZ3sZJBDZ0/Splash?node-id=0%3A1&t=dIKbToR8kEqIG5j3-0) with the latest work
