### ISSUE TITLE
add view previous auction functionality on the home page

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/public-assembly-home-page#40]
without getting into the full gov interface workflow, another low hanging fruit for the home page is prob the addition of back/forward arrows to see previous auction results. see screenshot below for example on nouns.wtf

<img width="298" alt="Screen Shot 2022-12-04 at 8 14 02 PM" src="https://user-images.githubusercontent.com/93691906/205528497-e2c684e3-6c54-47f6-9765-fef550ad6ca5.png">

for our implementation, I believe we could just throw the arrows below the "Public Assembly #x" ttitle and then add another row of blank space below. when viewing tokens that have alrady been distributed, I think we need to add in the following info:

1. who owns that token (which isnt necessarily the same as who won the auction)
2. how much did that token sell for. if it was a founders allocated token, that should be made apparent, rather than just having a weird 0eth / N/A price view

<img width="329" alt="Screen Shot 2022-12-04 at 8 15 24 PM" src="https://user-images.githubusercontent.com/93691906/205528627-3c8b216a-fa4d-4be9-8493-7c7e201d2df9.png">

**Comment by dblodorn** [comment]
Yeah good shout @0xTranqui .
Should also have a page with the token grid.
And show who current top bidder is.

**Comment by ioeylim** [comment]
@0xTranqui 
![LANDING](https://user-images.githubusercontent.com/113192435/206036813-dcf16ea6-bf6f-40fd-8578-71eda72c2ff6.png)
![LANDING2](https://user-images.githubusercontent.com/113192435/206036817-796a72c4-b9bf-4390-afda-9916076ec1c7.png)
