### ISSUE TITLE
Logic issues in TokenExplorer due to burned tokens

### ISSUE THREAD

**Issue by breath-imager** [public-assembly/public-assembly-home-page#53]
Hello PA'ers. 

I'm trying to integrate your @daoutils package into the web app for our collection (0xc230ba378d2d63da003CD5598642D72c6ba42d1E)  and discovered some bugs in the logic due to the fact that our collection has a few tokens that were burned (no one bid on them before the auction time ended). Therefore throwing off the Total Supply which doesn't count the burned tokens.

This means that anywhere where tokenSupply - 1 is being used as a comparator or to set the tokenId fails
ie

line 32:     totalSupply && setTokenId(totalSupply - 1)

line 36: if (totalSupply && tokenId < totalSupply - 1) {

line 51:tokenId === totalSupply - 1

line 64:           className={`${tokenId === totalSupply - 1 && 'pointer-events-none opacity-20'}`}

**Comment by 0xTranqui** [comment]
hey just figured out the answer for this. we should be hitting the aggregateStat query on the zora indexer, which will return the total number of nfts that have existed for that token. @breath-imager can you confirm that the correct number for total refraction tokens ever minted should be 67 (screenshot taken at 10:10 pm EST thursday march 2). query to get this is in the screenshot below

<img width="1099" alt="Screen Shot 2023-03-02 at 10 10 43 PM" src="https://user-images.githubusercontent.com/93691906/222621839-460d03e9-2b35-4992-9e42-f09ae96089e4.png">

@salieflewis do u think u could potentially get this into dao-utils?

**Comment by breath-imager** [comment]
> hey just figured out the answer for this. we should be hitting the aggregateStat query on the zora indexer, which will return the total number of nfts that have existed for that token. @breath-imager can you confirm that the correct number for total refraction tokens ever minted should be 67 (screenshot taken at 10:10 pm EST thursday march 2). query to get this is in the screenshot below
> 
> <img alt="Screen Shot 2023-03-02 at 10 10 43 PM" width="1099" src="https://user-images.githubusercontent.com/93691906/222621839-460d03e9-2b35-4992-9e42-f09ae96089e4.png">
> 
> @salieflewis do u think u could potentially get this into dao-utils?

You are correct!

**Comment by salieflewis** [comment]
This should be resolved with dao-utils@0.0.9
